Section "ServerFlags"
  Option "AutoAddDevices" "false"
  Option "AutoEnableDevices" "false"
  Option "AutoAddGPU" "false"
  Option "DontVTSwitch" "true"
  Option "AllowMouseOpenFail" "true"
EndSection

Section "Device"
  Identifier "P90 psbfb"
  Driver "fbdev"
  Option "fbdev" "/dev/graphics/fb0"
  Option "ShadowFB" "true"
EndSection

Section "Monitor"
  Identifier "P90 DSI panel"
EndSection

Section "Screen"
  Identifier "P90 screen"
  Device "P90 psbfb"
  Monitor "P90 DSI panel"
  DefaultDepth 24
  SubSection "Display"
    Depth 24
    Modes "1080x1920"
  EndSubSection
EndSection

Section "InputDevice"
  Identifier "P90 touchscreen"
  Driver "libinput"
  Option "Device" "/dev/input/event2"
  Option "Touchscreen" "on"
EndSection

Section "ServerLayout"
  Identifier "P90 layout"
  Screen "P90 screen"
  InputDevice "P90 touchscreen" "CorePointer"
EndSection
